package main

const outFileTemplate = `// Code generated by zipper tool; DO NOT EDIT.

package {{.pkg}}

import (
	"archive/zip"
	"bytes"
	"encoding/base64"
	"net/http"

	"golang.org/x/tools/godoc/vfs/httpfs"
	"golang.org/x/tools/godoc/vfs/zipfs"
)

var {{.var}} []byte

func New{{.var}}FS() http.FileSystem {
	zipReader, err := zip.NewReader(bytes.NewReader({{.var}}), int64(len({{.var}})))
	if err != nil {
		panic(err)
	}

	return httpfs.New(zipfs.New(&zip.ReadCloser{Reader: *zipReader}, "/"))
}

func init() {
	var err error
	{{.var}}, err = base64.StdEncoding.DecodeString(encodedData)
	if err != nil {
		panic(err)
	}
}

const encodedData = ` + "`{{.data}}`" + `
`
